type Phone {
  """
  id записи
  """
  id: ID
  """
  Номмер телефона
  """
  number: String
  """
  Имя владельца телефона
  """
  name: String
}
"""
Получить список всех телефонов
"""
type Query {
  readPhones: [Phone]
}
"""
Специальный тип данных для ввода
"""
input inputPhone {
  id: String
  number: String!
  name: String
}

type Mutation {
  """
  Добавить запись телефона
  """
  createPhone(input: inputPhone): Phone
  """
  Удалить запись о телефоне
  """
  deletePhone(id: String): Phone
  """
  Обновить запись о телефоне
  """
  updatePhone(input: inputPhone): Phone
}

